# Generated by Django 5.0.3 on 2024-03-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_default_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
