# Generated by Django 5.0.3 on 2024-03-24 21:36

import shared.models.tags
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0003_profile_nullable_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=shared.models.tags.TagsField(default=list),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="tags",
            field=shared.models.tags.TagsField(default=list),
        ),
    ]
