# Generated by Django 5.0.3 on 2024-03-26 21:04

from typing import Type
import django.db.models.deletion
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def profile_user_forward(apps, schema_editor):
    User: Type[AbstractUser] = apps.get_model("authentication", "User")
    Profile: Type[models.Model] = apps.get_model("resume", "Profile")

    # If there's no profile, there's no need to go further
    if Profile.objects.count() == 0:
        return

    superusers = list(User.objects.filter(is_superuser=True))
    if len(superusers) != 1:
        raise ValueError(
            "There must be exactly 1 superuser to apply this migration!"
        )

    user = superusers[0]

    if (
        not user.first_name
        and not user.last_name
        and (profile := Profile.objects.first())
    ):
        user.first_name = profile.first_name
        user.last_name = profile.last_name
        user.profile_url = profile.image_url
        user.save()

    Profile.objects.update(user=user)


def profile_user_backward(apps, schema_editor):
    User: Type[AbstractUser] = apps.get_model("authentication", "User")
    Profile: Type[models.Model] = apps.get_model("resume", "Profile")

    def user_val(field):
        return Subquery(
            User.objects.filter(pk=OuterRef("user_id")).values(field)[:1]
        )

    Profile.objects.select_related("user").update(
        first_name=user_val("first_name"),
        last_name=user_val("last_name"),
        image_url=user_val("profile_url"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0006_profile_introduction"),
        ("authentication", "0002_user_profile_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(
            profile_user_forward,
            profile_user_backward,
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
