# Generated by Django 5.0.3 on 2024-03-27 17:31

from typing import Type
import django.db.models.deletion
from django.db.models import Model
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import AbstractUser


def set_users(apps, schema_editor):
    User: Type[AbstractUser] = apps.get_model("authentication", "User")
    Project: Type[Model] = apps.get_model("resume", "Project")
    WorkExperience: Type[Model] = apps.get_model("resume", "WorkExperience")

    # If there's no Project adn WorkExperience, there's no need to go further
    if Project.objects.count() == 0 and WorkExperience.objects.count() == 0:
        return

    superusers = list(User.objects.filter(is_superuser=True))
    if len(superusers) != 1:
        raise ValueError(
            "There must be exactly 1 superuser to apply this migration!"
        )

    user = superusers[0]

    Project.objects.update(user=user)
    WorkExperience.objects.update(user=user)

    pass


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0007_profile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(set_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="user",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
