# Generated by Django 5.0.3 on 2024-03-27 20:35
from datetime import date
from typing import Type

from django.contrib.auth.models import AbstractUser
from django.db import migrations, models
from django.db.models import Model, Subquery, OuterRef
from django.db.models.functions import Coalesce


def set_user_birth_dates(apps, schema_editor):
    User: Type[AbstractUser] = apps.get_model("authentication", "User")
    Profile: Type[Model] = apps.get_model("resume", "Profile")

    birthday_sq = Subquery(
        Profile.objects.filter(user_id=OuterRef("id")).values("birth_date")[:1]
    )

    User.objects.filter(birth_date=None).update(birth_date=birthday_sq)


def set_profile_birth_dates(apps, schema_editor):
    User: Type[AbstractUser] = apps.get_model("authentication", "User")
    Profile: Type[Model] = apps.get_model("resume", "Profile")

    Profile.objects.update(
        birth_date=Coalesce(
            Subquery(
                User.objects.filter(pk=OuterRef("user_id")).values("birth_date")[:1]
            ),
            date(year=2000, month=1, day=1),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_project_workexperience_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(set_user_birth_dates, set_profile_birth_dates),
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
    ]
