# Generated by Django 5.0.3 on 2024-03-29 12:10

import django.db.models.deletion
import django_bleach.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0010_profile_contact_info_removed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("introduction", models.CharField(max_length=255, null=True)),
                ("text", django_bleach.models.BleachField()),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="cover_letters", to="resume.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_experiences",
                    models.ManyToManyField(
                        related_name="cover_letters", to="resume.workexperience"
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
    ]
