# Generated by Django 5.0.3 on 2024-03-29 14:26

import shared.models.tags
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0011_cover_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=shared.models.tags.TagsField(default=list, max_length=500),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="tags",
            field=shared.models.tags.TagsField(default=list, max_length=500),
        ),
    ]
