# Generated by Django 5.0.3 on 2024-04-01 14:15

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0012_tagsfield_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_me",
            field=django_bleach.models.BleachField(blank=True),
        ),
    ]
