# Generated by Django 5.0.3 on 2024-05-31 17:19

import django.db.models.deletion
from django.db import migrations, models


def _migrate_forward(apps, schema_editor):
    ProfileModel = apps.get_model("resume", "Profile")
    for profile in ProfileModel.objects.all():
        profile.projects.set(profile.projects_old.all())


def _migrate_backward(apps, schema_editor):
    ProfileModel = apps.get_model("resume", "Profile")
    for profile in ProfileModel.objects.all():
        profile.projects_old.set(profile.projects.all())


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0013_profile_about_me_allow_blank"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.profile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.project",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("profile", "project")},
            },
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="projects",
            new_name="projects_old",
        ),
        migrations.AlterField(
            model_name="profile",
            name="projects_old",
            field=models.ManyToManyField(
                related_name="profiles_old",
                to="resume.Project",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="projects",
            field=models.ManyToManyField(
                related_name="profiles",
                through="resume.ProfileProject",
                to="resume.project",
            ),
        ),
        migrations.RunPython(_migrate_forward, _migrate_backward),
        migrations.RemoveField(
            model_name="profile",
            name="projects_old",
        ),
    ]
