# Generated by Django 5.0.3 on 2024-05-31 17:50

import django.db.models.deletion
from django.db import migrations, models


def _migrate_forward(apps, schema_editor):
    ProfileModel = apps.get_model("resume", "Profile")
    for profile in ProfileModel.objects.all():
        profile.work_experiences.set(profile.work_experiences_old.all())


def _migrate_backward(apps, schema_editor):
    ProfileModel = apps.get_model("resume", "Profile")
    for profile in ProfileModel.objects.all():
        profile.work_experiences_old.set(profile.work_experiences.all())


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0014_profile_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileWorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.profile",
                    ),
                ),
                (
                    "work_experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.workexperience",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("profile", "work_experience")},
            },
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="work_experiences",
            new_name="work_experiences_old",
        ),
        migrations.AlterField(
            model_name="profile",
            name="work_experiences_old",
            field=models.ManyToManyField(
                related_name="profiles_old",
                to="resume.workexperience",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_experiences",
            field=models.ManyToManyField(
                related_name="profiles",
                through="resume.ProfileWorkExperience",
                to="resume.workexperience",
            ),
        ),
        migrations.RunPython(_migrate_forward, _migrate_backward),
        migrations.RemoveField(
            model_name="profile",
            name="work_experiences_old",
        ),
    ]
