# Generated by Django 5.0.3 on 2024-03-22 14:14

import django_bleach.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", django_bleach.models.BleachField()),
                ("links", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("description", django_bleach.models.BleachField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("links", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("about_me", django_bleach.models.BleachField()),
                ("job_title", models.CharField(max_length=255)),
                ("image_url", models.URLField()),
                ("birth_date", models.DateField()),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("looking_for_job", "Looking For Job"),
                            ("employed", "Employed"),
                            ("freelancer", "Freelancer"),
                        ],
                        max_length=15,
                    ),
                ),
                ("contact_info", models.JSONField(default=list)),
                ("skills", models.JSONField(default=list)),
                ("interests", models.JSONField(default=list)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="profiles", to="resume.project"
                    ),
                ),
                (
                    "work_experiences",
                    models.ManyToManyField(
                        related_name="profiles", to="resume.workexperience"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_profile",
            ),
        ),
    ]
