# Generated by Django 5.0.3 on 2024-03-27 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_user_profile_url"),
        ("resume", "0007_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_url",
            new_name="profile_image",
        ),
    ]
