# Generated by Django 5.0.3 on 2024-03-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_birthdate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_info",
            field=models.JSONField(default=list),
        ),
    ]
