name: CD-Liara
on:
    push:
        tags:
            - "v*.*.*"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install @liara/cli
              run: npm i -g @liara/cli@5

            - name: Generate requuirements.txt
              run: bash ./generate-requirements.sh

            - name: Deploy
              env:
                  LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
                  LIARA_APP_NAME: ${{ secrets.LIARA_APP_NAME }}
              run: liara deploy --app="${LIARA_APP_NAME}" --path ./resume_api --api-token="$LIARA_TOKEN" --no-app-logs
