name: CD-Liara
on:
    push:
        tags:
            - "v*.*.*"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: update-liara
              env:
                  LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
                  LIARA_APP_NAME: ${{ secrets.LIARA_APP_NAME }}
              run: |
                  npm i -g @liara/cli@5
                  liara deploy --app="${LIARA_APP_NAME}" --path ./resume_api --api-token="$LIARA_TOKEN" --no-app-logs
